out_dir: results
num_workers: 3
dataset:
  format: PyG
  name: PATTERN
  task: graph
  task_type: classification
  node_encoder: false
  edge_encoder: false
  split_mode: random
  split: [0.6, 0.2, 0.2]
share:
  num_splits: 3
train:
  batch_size: 128
  eval_period: 1
  ckpt_period: 50
  sampler: full_batch
model:
  type: hpoolgnn
  loss_fun: cross_entropy
  aux_loss: True
  gradient_clip_val: 0.2
gnn:
  layers_pre_mp: 1
  dim_inner: 32
  layer_type: sageconv
  stage_type: hierarchical_pooling
  batchnorm: False
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: false
  layer_normalize: true
  head: hpool_head
hierarchical_pooling:
  type: diffpool
  pool_ratio: 0.25
  flat_pooling: max
  num_post_pool_layers: 1
diffpool:
  num_blocks: 2
  num_block_mp_layers: 3
  num_block_pooling_layers: 3
mlp_head:
  num_layers: 2
  dropout: 0.0
optim:
  optimizer: adam
  base_lr: 0.05
  max_epoch: 2