out_dir: results
num_workers: 3
dataset:
  format: PyG
  name: TU_MUTAG
  task: graph
  task_type: classification
  node_encoder: false
  edge_encoder: false
  split_mode: random
  split: [0.6, 0.2, 0.2]
share:
  num_splits: 3
train:
  batch_size: 128
  eval_period: 1
  ckpt_period: 50
  sampler: full_batch
model:
  type: hpoolgnn
  loss_fun: cross_entropy
  aux_loss: true
  gradient_clip_val: 0.2
gnn:
  layers_pre_mp: 0
  layers_mp: 2
  layers_post_mp: 0
  dim_inner: 16
  layer_type: graphconv
  stage_type: hierarchical_pooling
  batchnorm: false
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: false
  head: hpool_head
hierarchical_pooling:
  type: mincutpool
  pool_ratio: 0.5
  flat_pooling: mean
mlp_head:
  num_layers: 2
  dropout: 0.0
optim:
  optimizer: adam
  base_lr: 0.01
  max_epoch: 20
